### ISSUE TITLE
Profile Alias'

### ISSUE THREAD

**Issue by jobhax25** [MartineauUK/wireguard#1]
Hello, I had a Issue when I installed earlier versions and updated when you added new profile alias' it said this " Warning: Aliases and shell functions for S50wireguard already exist" even though you added an additional alias. To fix I had erased all your aliases and re downloaded it and fixed. FYI I didn't have wgm. 

Maybe add a check for an existing one?

![image](https://user-images.githubusercontent.com/57541289/110257912-9ac5a280-7f65-11eb-868a-1d9e4bc4d5aa.png)

**Comment by MartineauUK** [comment]
Thank you for the feedback.

I rewritten the script and v2.01 it is now called 'wg_manager'

It is now menu driven, and isolates itself into the Addons repository (coming to amtm soon!)

So during the install, the script now creates an instant alias 'wg_manager' that is effective immediately (no need to logout/login to use it), and as 'wg_manager' is a bit lengthy to type, a short alias 'wgm' is created, but this doesn't become effective until you logout/login to the SSH session.

**Comment by jobhax25** [comment]
Thanks so Much! Great work by the way :)
