### ISSUE TITLE
RT-N66U C1

### ISSUE THREAD

**Issue by Deadfuntik** [MartineauUK/wireguard#10]
The rt-n66u c1 router firmware is from Merlin ac68u, I would like to install wireguard on it. Really?![image](https://user-images.githubusercontent.com/74204622/221376483-cea227a8-7881-49fc-b5f7-b9fd931fedf0.jpeg)

**Comment by MartineauUK** [comment]
WireGuard requires Kernel support, i.e. **v4.xx**

RT-N66U probably still uses Kernel **v2.36?**

You can check by issuing command:

`uname -r`

**Comment by Deadfuntik** [comment]
Thanks)
