### ISSUE TITLE
 "***ERROR: WireGuard 'client' doesn't have a LOCAL IP Address! - try 'peer wg11 ip=xxx.xxx.xxx.xxx/32'?" for PiVPN config but not mullvad VPN

### ISSUE THREAD

**Issue by chengus** [MartineauUK/wireguard#12]
I want to set my router as a client and route all traffic to my router at my secondary home. I have set up a wireguard 'server' on a raspberry pi at my secondary home, and tested it with devices it works. However, when I try the Import .conf from my raspberry pi in the wireguard manager on my ac86u, it gives me this error "***ERROR: WireGuard 'client' doesn't have a LOCAL IP Address! - try 'peer wg11 ip=xxx.xxx.xxx.xxx/32'?", but when I import a .conf from mullvad VPN it successfully connects. What am I missing here? Thanks in advance.

My conf from raspberry pi :

[Interface]
PrivateKey = xxx
Address = 10.187.54.7/24
DNS = 9.9.9.9, 149.112.112.112

[Peer]
PublicKey = xxx
PresharedKey = c2d+GBTdN0qpeKFoQwXWWjUilD9Mz8vp/wD3nwirwiA=
Endpoint = 218.250.20.159:51820
AllowedIPs = 0.0.0.0/0

My conf from mullvad:

[Interface]
# Device: Brave Gnu
PrivateKey = xxx
Address = 10.67.48.5/32,fc00:bbbb:bbbb:bb01::4:3004/128
DNS = 10.64.0.1

[Peer]
PublicKey = xxx
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = 146.70.201.66:51820

**Comment by MartineauUK** [comment]
The address assigned by Mullvad is nnn.nnn.nnn.nnn/32 I.e a single address


Your Raspi is supplying a subnet nnn.nnn.nnn.nnn/24

**Comment by chengus** [comment]
got it working, thanks man
