### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by gctcxu** [MartineauUK/wireguard#15]
Hey, I encounter problem when installing Wireguard

Device: ASUS RT-AX56U
Kernel: 4.1.xxx
Error: ffs/addons/wireguard/wg_manager.sh: source: line 7845: can't open '/usr/sbin/helper.sh

**Comment by MartineauUK** [comment]
'/usr/sbin/helper.sh' is included in the

**Comment by MartineauUK** [comment]
'/usr/sbin/helper.sh' is included in the [RMerlin custom firmware](https://www.asuswrt-merlin.net/)

If you are not running RMerlin firmware, then you would need to alter the calls to 'helper.sh' to execute the raw 'sed' commands.
