### ISSUE TITLE
Add/use my mullvad key 

### ISSUE THREAD

**Issue by Tchumeda** [MartineauUK/wireguard#2]
Thank u for the great job. U made my day.  I am a newbee. My issue is how to  use my mullvad account key on it. I have installed and created a peer device but i see a random key that genaretes during the creation or what i am i missing. Thks
One again i am greatfull

**Comment by MartineauUK** [comment]
General support questions/user 'Howto' queries are best answered in the thread by the community:

[https://www.snbforums.com/threads/session-manager.70787/](url)

However....

When using the router as a WireGuard Server, creation of a Road-Warrior 'device' Peer will create a unique key-pair for the router/device.

When using the router as a 'client to access Mullvad WireGuard servers, then a config file is created by the Mullvad configurator

[https://mullvad.net/en/account/#/wireguard-config/](url)

The resulting .config file can be imported into WireGuard_Manager using the 'import' command

**Comment by Tchumeda** [comment]
Thank u so much.On May 26, 2021 17:35, MartineauUK ***@***.***> wrote:
Closed #2.
