### ISSUE TITLE
keep getting the same error message

### ISSUE THREAD

**Issue by geoffroyguich** [MartineauUK/wireguard#4]
Hi 

I have tried several Wireguard Conf, that do work on wg client on mac, android etc..., but I keep getting this message : line unrecognized .... on the address of Interface.

Here is my conf file (XXX hidden)

[Interface]
Address = 10.0.10.13/32
PrivateKey = XXXXXX
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = XXXXXX
Endpoint = XXX.dyndns.org:XXX
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25

And here is the error message I get on wg.

Requesting WireGuard VPN Peer start (par2)

	wireguard-clientpar2: Initialising Wireguard VPN 'client' Peer (par2) to XXX.dyndns.org:XXX (# Unidentified) DNS=
Line unrecognized: `Address=10.0.10.13/32'
Configuration parsing error
	wireguard-clientpar2: Initialisation complete.

 	WireGuard ACTIVE Peer Status: Clients 1, Servers 0 

Can you help me with this?

Regards
Geoffroy

**Comment by MartineauUK** [comment]
You need to import the vendor supplied .conf file to create wg11.conf for
use on Asus routers

**Comment by MartineauUK** [comment]
WireGuard .conf files need to be pre-processed to strip/ignore directives that are not recognised by the Kernel Module/Uswrspace Tools

Normally wg-quick is used.

However, wireguard_manager does this during the 'import' phase and comments out the appropriate directives

e.g. You would need to copy 'par2.conf' to '/opt/etc/wireguard.d/'

`e  = Exit Script [?]

E:Option ==> import ?

	 Available Peer Configs for import:

par2.conf`

then

`e  = Exit Script [?]

E:Option ==> import par2

	[✔] Config par2 import as wg16 success

	Peers (Auto=P - Policy, Auto=X - External i.e. Cell/Mobile)
Server  Auto  Subnet        Port   Annotate
wg21    Y     10.50.1.1/24  51820  # RT-AC86U Server #1

Client  Auto  IP                                                Endpoint                       DNS             MTU  Annotate
wg11    N     10.0.10.13/32                                     XXX.dyndns.org:XXX             1.0.0.1              # N/A
`

**Comment by geoffroyguich** [comment]
Thank you. All good managed to get it to work.

I just set up another AC86U as server, just need to change the default listening port to something else than 51820, like 51821, what file do i need to append wg21?

Thank you so much for your help.

Amazing script!

Kind regards
Geoffroy


On January 10, 2022 at 2:58:21 PM, MartineauUK ***@***.***) wrote:

WireGuard .conf files need to be pre-processed to strip/ignore directives that are not recognised by the Kernel Module/Uswrspace Tools

Normally wg-quick is used.

However, wireguard_manager does this during the 'import' phase and comments out the appropriate directives

e.g. You would need to copy 'par2.conf' to '/opt/etc/wireguard.d/'

`e = Exit Script [?]

E:Option ==> import ?

 Available Peer Configs for import:

par2.conf`

then

`e = Exit Script [?]

E:Option ==> import par2

[✔] Config par2 import as wg16 success



Peers (Auto=P - Policy, Auto=X - External i.e. Cell/Mobile)

Server Auto Subnet Port Annotate
wg21 Y 10.50.1.1/24 51820 # RT-AC86U Server #1

Client Auto IP Endpoint DNS MTU Annotate
wg11 N 10.0.10.13/32 XXX.dyndns.org:XXX 1.0.0.1 # N/A
`

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MartineauUK** [comment]
You can change the 'server' Peer port using command

`
e  = Exit Script [?]

E:Option ==> peer wg21 port=51821

	[✔] Updated 'server' Peer Listen Port

`

or create a second 'server' Peer which listens on a different port

`
e  = Exit Script [?]

E:Option ==> peer new 

	*** Ensure Upstream router Port Foward entry for port:11502 ***

	Press y to Create (IPv6) 'server' Peer (wg22) 10.50.2.1/24:11502 or press [Enter] to SKIP.
y
	Creating WireGuard Private/Public key-pair for (IPv6) 'server' Peer wg22 on RT-AC86U (v386.4_0)
	Press y to Start (IPv6) 'server' Peer (wg22) or press [Enter] to SKIP.
y

	Requesting WireGuard VPN Peer start (wg22)

`

**Comment by geoffroyguich** [comment]
Fantastic. Thank you very much.




On Monday, January 10, 2022, 18:40, MartineauUK ***@***.***> wrote:




You can change the 'server' Peer port using command

`
e = Exit Script [?]

E:Option ==> peer wg21 port=51821
[✔] Updated 'server' Peer Listen Port

`

or create a second 'server' Peer which listens on a different port

`
e = Exit Script [?]

E:Option ==> peer new
*** Ensure Upstream router Port Foward entry for port:11502 ***

Press y to Create (IPv6) 'server' Peer (wg22) 10.50.2.1/24:11502 or press [Enter] to SKIP.

y
Creating WireGuard Private/Public key-pair for (IPv6) 'server' Peer wg22 on RT-AC86U (v386.4_0)
Press y to Start (IPv6) 'server' Peer (wg22) or press [Enter] to SKIP.
y
Requesting WireGuard VPN Peer start (wg22)

`

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
