### ISSUE TITLE
WireGuard Mgr v4.15 by amtm 3.2.3 on GT-AXE11000 (aarch64) FW-386.5

### ISSUE THREAD

**Issue by jagga99** [MartineauUK/wireguard#5]
Script was installed on my device but its launch giving me the following error:

1  = Begin WireGuard Installation Process
e  = Exit Script [?]
E:Option ==> 1
modprobe: module wireguard not found in modules.dep

Any ideas how to resolve this? thanks

**Comment by jagga99** [comment]
I got the following log of error:



```
 WireGuard ACTIVE Peer Status: Clients 0, Servers 0
1  = Begin WireGuard Installation Process
e  = Exit Script [?]
E:Option ==> 1

        Installing WireGuard Manager - Router GT-AXE11000 (v386.5_0) arch=aarch64

        Downloading scripts
        wg_client downloaded successfully
        wg_server downloaded successfully
        UDP_Updater.sh downloaded successfully
        wg_ChkEndpointDDNS.sh downloaded successfully
        wgmExpo.sh downloaded successfully

Package column (2.37-1) installed in root is up to date.
Package coreutils-mkfifo (8.32-6) installed in root is up to date.
Package p7zip (16.02-3) installed in root is up to date.
        Downloading Wireguard Kernel module for GT-AXE11000 (v386.5_0)
modprobe: module wireguard not found in modules.dep
```

**Comment by MartineauUK** [comment]
The ASUS v386 RC3-3 Beta seems to have support for GT-AX11000
https://www.snbforums.com/threads/asuswrt-386-rc3-3-public-beta-for-ipv6-ddns-and-ipv6-vpn-server.75829/

So I would hope that ASUS did include the WireGuard Kernel modules....only way to prove it would be for you to temporarily load the v386 RC3-3 Beta.

You could try searching for the module, and if found, manually attempt to load it

find /lib/modules -name "wireguard.ko" 

e.g. /lib/modules/4.1.52/kernel/net/wireguard/wireguard.ko

insmod wireguard.ko

insmod: can't insert '/lib/modules/4.1.52/kernel/net/wireguard/wireguard.ko': File exists ( i.e. on my router it is alraedy loaded from the location shown)

However, @ZebMcKayhan compiled a module....

https://github.com/ZebMcKayhan/Wireguard
https://github.com/ZebMcKayhan/Wireguard#rt-ax88u--gt-ax11000

Don't know if this is the same model as yours?

**Comment by MartineauUK** [comment]
Issue the following commands to determine the model string used by wireguard_manager installer routine

nvram get odmpid
nvram get productid

**Comment by MartineauUK** [comment]
NOTE to self..weekend drink affects postings...

https://rog.asus.com/networking/rog-rapture-gt-axe11000-model/spec

No WireGuard VPN is shown as supported - RMerlin did compile the modules in his release.

**Comment by jagga99** [comment]
nvram get productid:
GT-AXE11000

nvram get odmpid: 
received nothing

find /lib/modules -name "wireguard.ko" - nothing on my router;

**Comment by jagga99** [comment]
if RMerlin included in firmware this module, why it is absent now?

**Comment by MartineauUK** [comment]
http://www.snbforums.com/threads/asuswrt-merlin-386-4-beta-is-now-available.76258/

You'll have to post a query with RMerlin

**Comment by jagga99** [comment]
tnx

**Comment by jagga99** [comment]
RMerlin told me: "Wireguard module and userspace tools are not available for the GT-AXE11000 in 386.5. They should be added in the next release."

**Comment by MartineauUK** [comment]
Hmmmmm, these recent post by RMerlin a few days ago doesn't inspire any urgency?

Basically his opinion is that OpenVPN is good enough on ASUS routers, so attempting to use WireGuard on ASUS routers is pointless :-(

http://www.snbforums.com/threads/wireguard-and-nordvpn.77685/post-748657
http://www.snbforums.com/threads/wireguard-and-nordvpn.77685/post-748717

**Comment by MartineauUK** [comment]
http://www.snbforums.com/threads/asuswrt-merlin-386-5-is-now-available.77691/post-752808

Asuswrt-Merlin 386/NG Changelog
===============================

386.5_2 (xx-xxx-2022)
  - UPDATED: openssl to 1.1.1n.
  - UPDATED: openvpn to 2.5.6.
  - CHANGED: Added Wireguard module + userspace tool to
             GT-AXE11000.
