### ISSUE TITLE
Errors while starting and stopping

### ISSUE THREAD

**Issue by purewooder** [MartineauUK/wireguard#6]
I have the following output while importing and restarting: 
```
	Requesting WireGuard VPN Peer restart (wg11)

	wireguard-clientwg11: Initialising Wireguard VPN 'client' Peer (wg11) to 192.168.57.10:33213 (# N/A) DNS=
/jffs/addons/wireguard/wg_client: local: line 605: not in a function
ip6tables v1.4.21: host/network `192.168.56.1' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
	wireguard-clientwg11: Initialisation complete.
```
this client peer cannot connect, while the same conf works well on my phone.

The default server wg21 works well, which I have tested on my phone.
But there are also problems stopping the peers as below.

```
	Requesting WireGuard VPN Peer stop (wg21 wg11)

Error: Address /jffs/addons/wireguard/wg_server is invalid

*** Usage:
 dw/dh/db <physical address in hex> <number>
 dw/dh/db <-k> <virtual address in hex> <number>
 sw/sh/sb <physical address in hex> <data value1> <data value2> ..<data valueN>
 sw/sh/sb <-k> <virtual address in hex> <data value1> <data value2> ..<data valueN>
 fw/fh/fb  <physical address in hex> <data value> <length>
 fw/fh/fb <-k> <virtual address in hex> <data value> <length>
  -s (currently works with physical addresses for d*/s*/f* commands
and virtual addresses for s*/f* commands)


Error: Address /jffs/addons/wireguard/wg_client is invalid

*** Usage:
 dw/dh/db <physical address in hex> <number>
 dw/dh/db <-k> <virtual address in hex> <number>
 sw/sh/sb <physical address in hex> <data value1> <data value2> ..<data valueN>
 sw/sh/sb <-k> <virtual address in hex> <data value1> <data value2> ..<data valueN>
 fw/fh/fb  <physical address in hex> <data value> <length>
 fw/fh/fb <-k> <virtual address in hex> <data value> <length>
  -s (currently works with physical addresses for d*/s*/f* commands
and virtual addresses for s*/f* commands)


 	WireGuard ACTIVE Peer Status: Clients 1, Servers 1
```

**Comment by MartineauUK** [comment]
Which **ASUS** Router/Firmware? and which version of `wireguard_manager` ? i.e. **v4.15** Stable or a **Beta v4.16b**?

If **v4.15** then that is embarrassing, but rogue Betas can slip through as I randomly dump the work-in-progress to GitHub dev branch as a backup.

I suggest you upgrade to the latest `wireguard_manager` **Beta v4.16b9** and retry.

NOTE:: On the basis of the weird errors that appear,  I suspect however, that your router firmware either isn't supported or the scripts are corrupt?

**Comment by MartineauUK** [comment]
What happens if you enter the following commands

`sh`
`sh ./test`

**Comment by purewooder** [comment]
I have RT-AX68U Firmware (v386.5_2). Before it was version  v4.15 Stable.
After `sh`, it showed nothing. And after `sh ./test`, it showed `sh: can't open './test'`.

I removed the installed wireguard_manager, and then reinstalled it. It is v4.16b9 now. And it works well.

Thank you!
