### ISSUE TITLE
WAN Speed Reduced with Wireguard Installed

### ISSUE THREAD

**Issue by mxmartins** [MartineauUK/wireguard#7]
I have a RT-AX86U running Merlin 386.5_2.  Prior to running this wireguard install scrip, the internet speed is 1.400 Mbps down and 42 Mbps up.  I used amtm to install entware on a 32GB usb memory stick,  Then, I ran the install wireguard script.  Everything installed fine and I added a few devices and they are able to connect to wireguard just fine.
However, the internet speed on the router after the entware/wireguard install is about half, bounces around between 500-700 Mbps down and the upload was reduced as well..  After some troubleshooting, I found out that if I shutdown the router, remove the USB memory stick (wireguard no longer works), the speeds are back to normal, prior to what they were before install.  Shutting down the router, reinserting the USB stick, and restarting the router again, the speeds go back to half again...
Is this a known issue?  Is there a work around to this problem?

**Comment by MartineauUK** [comment]
Known issue.

Many threads on the Small Net builder Forums (SNB)...

https://www.snbforums.com/threads/session-manager-discussion-thread-closed-expired-oct-2021-use-http-www-snbforums-com-threads-session-manager-discussion-2nd-thread-75129.70787/post-688282

H/W acceleration must be disabled on the router.....
https://www.snbforums.com/threads/wireguard-and-nordvpn.77685/post-748657

https://www.snbforums.com/threads/wireguard-and-nordvpn.77685/post-748705
