### ISSUE TITLE
WG stuck at idle

### ISSUE THREAD

**Issue by ajax1337** [MartineauUK/wireguard#8]
i have wgm installed on my Asus ax11000. unable to get wg working, always getting stuck at this screen.

Please help

![Screenshot_20220422-153306_Gallery](https://user-images.githubusercontent.com/67271356/164685152-f65c7170-13db-429e-9d00-ca8c026b5bad.png)

**Comment by MartineauUK** [comment]
Support should requested in the SNB forum thread....

e.g. See this post to see if the router is actually seeing any inbound requests.
https://www.snbforums.com/threads/session-manager-discussion-2nd-thread.75129/post-751825
