### ISSUE TITLE
Sep  5 10:59:00 (wg_manager.sh): 18319 Clients ^[[97m0^[[95m, Servers ^[[97m1

### ISSUE THREAD

**Issue by luluhoc** [MartineauUK/wireguard#9]
what does this log mean?

`Sep  5 10:59:00 (wg_manager.sh): 18319 Clients ^[[97m0^[[95m, Servers ^[[97m1`

**Comment by MartineauUK** [comment]
Normally in a console the message should appear like this:

![image](https://user-images.githubusercontent.com/27958379/189349223-c29a92c0-ef69-43cf-ba0f-522e7ad5886e.png)

The ANSI Escape colour Control characters to turn on/off the colours can be suppressed if your device cannot honour them

Use command
`color off`

Your Syslog (which cannot always honour the ANSI Escape colour Control sequences) message is telling you that there are zero ACTIVE 'client' Peers connected outbound, and one ACTIVE 'server' Peer listening for inbound connections, unlike mine where there are three ACTIVE 'client' Peers and two ACTIVE 'server' Peers.
